[env]
TERM = "xterm-256color"

[window]
padding.y = 0
startup_mode = "Maximized"
opacity = 0.8
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 11

[selection]
save_to_clipboard = true
